---
title: "AQI ETL"
author: "Katie Masiello"
date: "12/2/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pointblank)
library(dplyr)
library(lubridate)
library(pins)
```

Build the API query URL

```{r}
base_url <- "https://www.airnowapi.org/aq/data/"

# variable endpoints
# Query the API for current date and the last `timespan` hours
timespan <- 24 #hours
.now <- now("UTC")
.then <- .now - hours(timespan)

endDate <- paste0("endDate=",date(.now),"T",stringr::str_pad(hour(.now),width = 2,pad = 0))
startDate <- paste0("startDate=",date(.then),"T",stringr::str_pad(hour(.then),width = 2,pad = 0))

# constant endpoints
parameters <- "parameters=OZONE,PM25,PM10,CO,NO2,SO2"
boundingBox <- "BBOX=-123.146648,46.996876,-121.487713,48.204308"
dataType <- "dataType=B"
format <- "format=text/csv"
verbose <- "verbose=1"
nowcastonly <- "nowcastonly=1"
includeRaw <- "includerawconcentrations=1"
API_KEY <- paste0("API_KEY=",Sys.getenv("AIRNOW_API_KEY"))

url <- paste(paste0(base_url,"?",
                    startDate),
             endDate,
             parameters,
             boundingBox,
             dataType,
             format,
             verbose,
             nowcastonly,
             includeRaw,
             API_KEY,sep="&")
             
```

# Query the API

```{r}
response <- GET(url) %>% content(col_names = FALSE)

# put col names 
colnames(response) = c("Latitude", 
                      "Longitude",
                      "UTC",
                      "Pollutant",
                      "Concentration",
                      "Unit",
                      "Raw_Concentration",
                      "AQI",
                      "Category",
                      "Site_Name",
                      "Site_Agency",
                      "AQS_ID",
                      "Full_AWS_ID")

```

# explore

```{r}
scan_data(response)
```

# Define basic rules for data quality to ensure import assumptions are valid

```{r}
# Define a column schema so we can check inputted data is as expected
schema_aqi_table <- col_schema(Latitude = "numeric",
                               Longitude = "numeric",
                               UTC = c("POSIXct"),
                               Pollutant = "character",
                               Concentration = "numeric",
                               Unit = "character",
                               Raw_Concentration = "numeric",
                               AQI = "numeric",
                               Category = "numeric",
                               Site_Name = "character",
                               Site_Agency = "character",
                               AQS_ID = "numeric",
                               Full_AWS_ID = "numeric")
```

```{r}
agent <- create_agent(response) %>% col_schema_match(schema_aqi_table, is_exact = FALSE) %>% interrogate() 
all_passed(agent)
```

mid-day ozone is highest. see if range is

```{r}
agent <- create_agent(read_fn = ~response, label = "Air Quality Report") %>% 
  col_vals_between(columns = vars(Raw_Concentration), left = 1, right = 20, preconditions = ~. %>% dplyr::filter(Pollutant == "OZONE") 
                                                                                              ) %>% interrogate()
```

```{r}
(agent <- create_agent(read_fn = ~response, label = "Air Quality Report") %>% 
  col_vals_not_equal(vars(Raw_Concentration), value = -999) %>% interrogate() 
)
```

```{r}
agent %>% get_sundered_data(type = "fail") %>% View()

```
