---
title: "Email Document"
output: blastula::blastula_email
editor_options: 
  chunk_output_type: console
---

Breathe easy!  AQI measurements are all good for `r nrow(good_air)` measurements.


A sample of the most recent readings from 6 random sites:  

```{r echo=FALSE}
most_recent <- good_air %>% 
  group_by(Site_Name) %>% 
  slice(1) %>% ungroup() %>% 
  select(Site_Name, AQI, UTC, color)

sample_readings <- most_recent %>% sample_n(6)

ggplot(sample_readings, aes(fill = color, ymax = AQI/350, ymin = 0, xmax = 2, xmin = 1)) +
  geom_rect(aes(ymax=1, ymin=0, xmax=2, xmin=1), fill ="whitesmoke") +
  geom_rect() + 
  coord_polar(theta = "y",start=-pi/2) + xlim(c(0, 2)) + ylim(c(0,2)) +
  geom_text(aes(x = 0, y = 0, label = AQI, colour=color), size=5.5, family="Poppins SemiBold") +
  geom_text(aes(x=1.5, y=1.5, label=Site_Name), family="Poppins Light", size=3) + 
  facet_wrap(~Site_Name, ncol = 3) +
  theme_void() +
  scale_fill_manual(values = c(
    "green"="forestgreen","yellow"="yellow", "orange"="darkorange", 
    "red"="red", "purple"="purple1", "maroon"="red4")) +
  scale_colour_manual(values = c("green"="forestgreen","yellow"="yellow", "orange"="darkorange", 
                                 "red"="red", "purple"="purple1", "maroon"="red4")) +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  guides(fill=FALSE) +
  guides(colour=FALSE)
```

```{r echo=FALSE}
suppressMessages(library(gt))
```

The highest reading over the last `r timespan` hours is from the **`r tbl$Site_Name[1]`** site. This peak reading was **`r tbl$AQI[1]`**.  

 
Here's the trend at that site:  

```{r echo=FALSE}
site_plot
```



Here's a summary of the 20 highest readings over the last `r timespan` hours:

```{r echo=FALSE}
good_air %>% select(Site_Name, AQI, Pollutant, Concentration, Unit) %>% 
  arrange(desc(AQI)) %>% 
  head(20) %>% 
  group_by(Site_Name) %>% gt(rowname_col = "Pollutant") %>% 
  summary_rows(groups = TRUE, columns = c("AQI", "Concentration"), 
               fns = list(avg = ~mean(.))) %>% as_raw_html() 

```


`r xlist$report_html`