---
title: "Email Document"
output: blastula::blastula_email
editor_options: 
  chunk_output_type: console
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

There's some bad air out there, baby.  Mask up.  Air quality index exceeds `r threshold` for `r nrow(bad_air)` readings.  These are taken over the last `r timespan` hours. See the summary agent below and data attached.

```{r echo=FALSE}
suppressMessages(library(gt))
xlist$report_html
```
Here are top 30 highest readings:

```{r echo=FALSE}
bad_air %>% select(Site_Name, AQI, Pollutant, Concentration, Unit) %>% 
  arrange(desc(AQI)) %>% 
  head(30) %>% 
  group_by(Site_Name) %>% gt(rowname_col = "Pollutant") %>% 
  summary_rows(groups = TRUE, columns = vars("AQI", "Concentration"), 
               fns = list(avg = ~mean(.))) %>% as_raw_html() 

```


```{r echo=FALSE}
# library(reactable)
# 
# summary_tbl <- bad_air %>% select(Site_Name, AQI, Pollutant, Concentration, Unit) %>% arrange(desc(AQI))
# 
# reactable(summary_tbl, groupBy = c("Site_Name", "Pollutant"),
#           defaultSorted = c("AQI"),
#            minRows = 15, searchable = TRUE,
#           columns = list(
#             Site_Name = colDef(), 
#             AQI = colDef(aggregate = "mean", format = colFormat(digits = 0)),
#             Pollutant = colDef(aggregate = "unique"), 
#             Concentration = colDef(aggregate = "mean", format = colFormat(digits = 0)), 
#             Unit = colDef()
#           ))

```

